name: "pysoa"

services:
  slogin:
    container_name: slogin
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 5 && python -u slogin.py"
    networks:
      - shared_network

networks:
  shared_network:
    external: true